# src/elephant/__init__.py

"""A helpful SDK for interacting with the Elephant API."""

from .client import ElephantClient
from .exceptions import (
    ElephantAuthError,
    ElephantConfigError,
    ElephantDeprecatedError,
    ElephantError,
    ElephantHTTPError,
    ElephantNetworkError,
)
from .helpers import (
    EncounterFileRow,
    cohort_learners_from_csv,
    encounter_rows_from_csv,
    learners_from_csv,
    prepare_bulk_upload_by_id,
)
from .models import (
    ApiKey,
    ApiKeyCreateRequest,
    ApiKeyCreateResponse,
    ApiKeyRole,
    ApiKeyStatus,
    BulkLearnerEntry,
    BulkLearnerUpsertError,
    BulkLearnerUpsertErrorCode,
    BulkLearnerUpsertItem,
    BulkLearnerUpsertItemResult,
    BulkLearnerUpsertRequest,
    BulkLearnerUpsertResponse,
    BulkLearnerUpsertSummary,
    BulkUploadResponse,
    CohortLearnerLinkError,
    CohortLearnerLinkErrorCode,
    CohortLearnerUpsertResult,
    CohortLinkEntry,
    CohortUpsertRequest,
    CohortUpsertResponse,
    CohortUpsertSummary,
    CreateEncounterRequest,
    EncounterResponse,
    EncounterSearchRequest,
    EncounterSearchResponse,
    FileInfo,
    FileType,
    FileTypeCode,
    FileUploadResult,
    FileValidationRequest,
    FileValidationResponse,
    GroupedFiles,
    LearnerSummary,
    PresignedUrlResponse,
    Problem,
    SearchFilesRequest,
    UploadByIdBulkMeta,
    UploadByIdMeta,
    UploadSummary,
)
from .utils import FileToUpload, PreparedBulkById

# Define what `from elephant import *` imports, though explicit imports are better.
__all__ = [
    "ApiKey",
    "ApiKeyCreateRequest",
    "ApiKeyCreateResponse",
    "ApiKeyRole",
    "ApiKeyStatus",
    "BulkLearnerEntry",
    "BulkLearnerUpsertError",
    "BulkLearnerUpsertErrorCode",
    "BulkLearnerUpsertItem",
    "BulkLearnerUpsertItemResult",
    "BulkLearnerUpsertRequest",
    "BulkLearnerUpsertResponse",
    "BulkLearnerUpsertSummary",
    "BulkUploadResponse",
    "CohortLearnerLinkError",
    "CohortLearnerLinkErrorCode",
    "CohortLearnerUpsertResult",
    "CohortLinkEntry",
    "CohortUpsertRequest",
    "CohortUpsertResponse",
    "CohortUpsertSummary",
    "CreateEncounterRequest",
    "ElephantAuthError",
    "ElephantClient",
    "ElephantConfigError",
    "ElephantDeprecatedError",
    "ElephantError",
    "ElephantHTTPError",
    "ElephantNetworkError",
    "EncounterFileRow",
    "EncounterResponse",
    "EncounterSearchRequest",
    "EncounterSearchResponse",
    "FileInfo",
    "FileToUpload",
    "FileType",
    "FileTypeCode",
    "FileUploadResult",
    "FileValidationRequest",
    "FileValidationResponse",
    "GroupedFiles",
    "LearnerSummary",
    "PreparedBulkById",
    "PresignedUrlResponse",
    "Problem",
    "SearchFilesRequest",
    "UploadByIdBulkMeta",
    "UploadByIdMeta",
    "UploadSummary",
    "cohort_learners_from_csv",
    "encounter_rows_from_csv",
    "learners_from_csv",
    "prepare_bulk_upload_by_id",
]

# You can also set the package version here, pulling it from metadata if desired
__version__ = "3.1.1"
