# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-11T01:08:33+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Dict, List, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel


class ApiKeyRole(Enum):
    admin = "admin"
    read_write_delete = "read_write_delete"
    read_write = "read_write"
    read_only = "read_only"
    read_only_restricted = "read_only_restricted"


class ApiKeyStatus(Enum):
    active = "active"
    revoked = "revoked"
    expired = "expired"
    inactive = "inactive"


class ApiKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key_id: UUID
    owner: str
    role: ApiKeyRole
    created_at: datetime
    revoked_at: Optional[datetime] = None
    last_used_at: Optional[datetime] = None
    is_active: bool
    expires_at: Optional[datetime] = None
    status: ApiKeyStatus


class ApiKeyCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    owner: Annotated[str, Field(min_length=1)]
    role: ApiKeyRole
    expires_at: Annotated[
        Optional[datetime],
        Field(
            description="If omitted and `never_expires` is false, the server applies the default API key expiration policy."
        ),
    ] = None
    never_expires: Annotated[
        Optional[bool],
        Field(
            description="Explicitly opt out of API key expiration. Mutually exclusive with `expires_at`."
        ),
    ] = False


class ApiKeyCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_key: Annotated[
        str,
        Field(description="Raw API key secret. Returned once and never stored in plaintext."),
    ]
    key: ApiKey


class Learner(BaseModel):
    learner_id: UUID
    learner_name: str
    email: EmailStr


class InvalidEncounter(BaseModel):
    encounter_id: UUID
    encounter_key: Optional[str] = None
    encounter_date: str
    file_count: int
    learners: List[Learner]


class FileValidationResponse(BaseModel):
    total_matching_encounters: int
    total_valid_encounters: int
    invalid_encounters: Annotated[
        List[InvalidEncounter],
        Field(description="Encounters where file counts don't match"),
    ]


class LearnerSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner_id: UUID
    learner_name: str
    email: str
    first_name: Optional[str] = None
    last_name: Optional[str] = None


class BulkLearnerUpsertItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    learner_name: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None


class BulkLearnerUpsertSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    created: int
    updated: int
    invalid: int
    duplicates: int
    errors: int


class BulkLearnerEntry(Enum):
    created = "created"
    updated = "updated"


class BulkLearnerUpsertErrorCode(Enum):
    invalid_input = "invalid_input"
    duplicate_in_batch = "duplicate_in_batch"


class MatchMode(Enum):
    exact = "exact"
    contains = "contains"
    prefix = "prefix"
    suffix = "suffix"


class CaseMode(Enum):
    insensitive = "insensitive"
    sensitive = "sensitive"


class TextFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str
    match_mode: Annotated[
        Optional[MatchMode],
        Field(description="If omitted, inherits defaults.match_mode (default: contains)."),
    ] = None
    case_mode: Annotated[
        Optional[CaseMode],
        Field(description="If omitted, inherits defaults.case (default: insensitive)."),
    ] = None


class CreateEncounterRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    case_name: str
    activity_name: str
    date: Annotated[str, Field(description="MM/DD/YYYY hh:mm a")]
    room: Optional[str] = None
    standardized_patients: Optional[str] = None
    additional_encounter_details: Optional[Dict[str, Any]] = None
    cohort_name: str
    learner_emails: Annotated[
        List[EmailStr],
        Field(
            description="All emails must already exist as learners; otherwise 404.",
            min_length=1,
        ),
    ]


class EncounterEntry(Enum):
    created = "created"
    reused = "reused"


class CaseEntry(Enum):
    created = "created"
    reused = "reused"


class ActivityEntry(Enum):
    created = "created"
    reused = "reused"


class EncounterResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    encounter_id: UUID
    encounter_key: str
    encounter_date: str
    encounter_timestamp: Optional[datetime] = None
    case_id: UUID
    case_name: str
    activity_id: UUID
    activity_name: str
    cohort_id: UUID
    cohort_name: str
    room: Optional[str] = None
    standardized_patients: Optional[str] = None
    additional_encounter_details: Optional[Dict[str, Any]] = None
    learners: List[LearnerSummary]
    encounter_entry: EncounterEntry
    case_entry: CaseEntry
    activity_entry: ActivityEntry


class SearchDefaults(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    match_mode: Optional[MatchMode] = MatchMode.contains
    case_mode: Optional[CaseMode] = CaseMode.insensitive


class TextOverrides1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner: Optional[TextFilter] = None
    case_name: Optional[TextFilter] = None
    activity_name: Optional[TextFilter] = None
    room: Optional[TextFilter] = None
    cohort: Optional[TextFilter] = None


class OrderBy(Enum):
    date_desc = "date_desc"
    date_asc = "date_asc"
    case_name = "case_name"
    activity_name = "activity_name"


class EncounterSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner: Optional[str] = None
    case_name: Optional[str] = None
    activity_name: Optional[str] = None
    date: Optional[str] = None
    room: Optional[str] = None
    cohort: Optional[str] = None
    encounter_id: Optional[UUID] = None
    learner_id: Optional[UUID] = None
    cohort_id: Optional[UUID] = None
    search_defaults: Optional[SearchDefaults] = None
    text_overrides: Optional[TextOverrides1] = None
    limit: Annotated[Optional[int], Field(ge=1)] = 50
    offset: Annotated[Optional[int], Field(ge=0)] = 0
    order_by: Optional[OrderBy] = OrderBy.date_desc
    require_unique: Optional[bool] = False


class EncounterSearchItem(BaseModel):
    encounter_id: UUID
    encounter_key: str
    encounter_date: str
    case_name: str
    activity_name: str
    case_id: UUID
    activity_id: UUID
    room: Optional[str] = None
    learners: List[Learner]
    cohort: str
    cohort_id: UUID
    additional_encounter_details: Optional[Dict[str, Any]] = None


class EncounterSearchResponse(BaseModel):
    total: int
    items: List[EncounterSearchItem]


class CohortUpsertRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cohort_name: str
    learner_emails: Annotated[
        List[EmailStr],
        Field(description="Existing learner emails to link to the cohort.", min_length=1),
    ]


class CohortEntry(Enum):
    created = "created"
    reused = "reused"


class CohortUpsertSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    linked: int
    already_linked: int
    not_found: int
    duplicates: int
    invalid: int
    errors: int


class CohortLinkEntry(Enum):
    linked = "linked"
    already_linked = "already_linked"


class CohortLearnerLinkErrorCode(Enum):
    not_found = "not_found"
    duplicate_in_batch = "duplicate_in_batch"
    invalid_input = "invalid_input"


class LearnerUpsertRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    learner_name: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None


class LearnerEntry(Enum):
    created = "created"
    updated = "updated"
    reused = "reused"


class FileInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_id: UUID
    file_path: AnyUrl
    file_type: Annotated[
        str,
        Field(
            description="File type code, from file_types.code, returned here as a string to not break if new types are added."
        ),
    ]
    size_bytes: int
    uploaded_at: datetime
    additional_file_identifier: Annotated[
        Optional[int],
        Field(description="Optional caller-defined integer identifier for this file."),
    ] = None
    file_hash: str
    og_file_name: Optional[str] = None


class GroupedFiles(BaseModel):
    learner: str
    learner_email: str
    learner_id: UUID
    case_name: str
    encounter_key: str
    activity_name: str
    room: str
    encounter_id: UUID
    encounter_date: str
    cohort: Optional[str] = None
    cohort_id: Optional[UUID] = None
    standardized_patients: Optional[str] = None
    additional_encounter_details: Optional[Dict[str, Any]] = None
    resources: List[FileInfo]


class FileUploadResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_name: str
    status: int
    message: str
    file_id: Optional[UUID] = None


class UploadSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    created: int
    duplicates: int
    errors: int


class BulkUploadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: UploadSummary
    results: List[FileUploadResult]


class PresignedUrlResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl


class Problem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Annotated[
        AnyUrl,
        Field(description='A URI identifying the problem type (or "about:blank").'),
    ]
    title: Annotated[str, Field(description="Short, human-readable summary of the problem type.")]
    status: Annotated[
        int, Field(description="HTTP status code for this occurrence of the problem.")
    ]
    detail: Annotated[
        Optional[str],
        Field(description="Human-readable explanation specific to this occurrence."),
    ] = None
    instance: Annotated[
        Optional[AnyUrl],
        Field(description="A URI reference that identifies the specific occurrence."),
    ] = None
    request_id: Annotated[
        Optional[str], Field(description="Mirrors X-Request-Id for correlation.")
    ] = None


class FileTypeCode(Enum):
    video = "video"
    audio = "audio"
    transcript_vtt = "transcript_vtt"
    transcript_srt = "transcript_srt"
    transcript_txt = "transcript_txt"
    transcript_metadata_json = "transcript_metadata_json"
    notes_txt = "notes_txt"
    notes_json = "notes_json"
    notes_md = "notes_md"
    annotations_json = "annotations_json"
    video_metadata_csv = "video_metadata_csv"
    notes_metadata_csv = "notes_metadata_csv"
    metadata_xlsx = "metadata_xlsx"
    log_file = "log_file"
    rubric_xlsx = "rubric_xlsx"
    rubric_json = "rubric_json"
    rubric_yaml = "rubric_yaml"
    group_manifest_json = "group_manifest_json"
    pipeline_prompt_output_json = "pipeline_prompt_output_json"
    pipeline_config_yaml = "pipeline_config_yaml"
    prompt_config_yaml = "prompt_config_yaml"
    other = "other"


class FileType(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Stable file type code from file_types.code.")]
    group_name: Annotated[str, Field(description="Human-readable grouping label.")]
    mime_primary: Annotated[
        str, Field(description="Primary MIME type associated with this file type.")
    ]
    description: Annotated[str, Field(description="Human-readable file type description.")]
    extensions: Annotated[
        List[str], Field(description="Typical file extensions for this file type.")
    ]
    is_user_visible: Annotated[
        bool,
        Field(description="Whether this type should be shown in user-facing pickers."),
    ]


class EncounterKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Deterministic key: SHA-256 over the payload `"sorted_lowercased_learners_csv-activity_name_lower-case_name_lower-date_lower"`, encoded as **base64url without padding**. - Learners are lowercased, trimmed, then **sorted** and joined with commas. - activity_name, case_name, date are lowercased + trimmed. - Example payload: `"alex johnson,priya singh-osce 1-renal block a-2025-03-14"`. - Output is 43 chars: `[A-Za-z0-9_-]{43}`.\n',
            examples=["0b2U7rT2mYh6y_0yK0qYgYx8Gd5m7N0bqS5s2f4yT7E"],
            pattern="^[A-Za-z0-9_-]{43}$",
        ),
    ]


class Defaults(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    match_mode: Optional[MatchMode] = MatchMode.contains
    case_mode: Optional[CaseMode] = CaseMode.insensitive


class TextOverrides(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner: Optional[TextFilter] = None
    case_name: Optional[TextFilter] = None
    activity_name: Optional[TextFilter] = None
    room: Optional[TextFilter] = None
    file_type: Optional[TextFilter] = None
    cohort: Optional[TextFilter] = None


class SearchFilesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner: Optional[str] = None
    case_name: Optional[str] = None
    activity_name: Optional[str] = None
    date: Optional[str] = None
    room: Optional[str] = None
    encounter_id: Optional[UUID] = None
    learner_id: Optional[UUID] = None
    file_type: Optional[FileTypeCode] = None
    cohort: Optional[str] = None
    limit: Annotated[
        Optional[int],
        Field(
            description="Maximum grouped rows to return. Omit to return all matches.",
            ge=1,
        ),
    ] = None
    offset: Annotated[
        Optional[int],
        Field(
            description="Number of grouped rows to skip. Applies with or without limit.",
            ge=0,
        ),
    ] = 0
    defaults: Annotated[
        Optional[Defaults],
        Field(
            description="Global defaults, contains case insensitive, applied to all text fields (uuid fields are exact match only) if no per-field override provided."
        ),
    ] = None
    text_overrides: Optional[TextOverrides] = None


class FileValidationRequest(BaseModel):
    case_name: str
    activity_name: str
    learner_emails: Annotated[
        Optional[List[EmailStr]],
        Field(
            description="Preferred participant selector. Encounters match when any participant email is in this list after lowercase/trim normalization.\n",
            min_length=1,
        ),
    ] = None
    learners: Annotated[
        Optional[List[str]],
        Field(
            description="Deprecated legacy participant selector by learner display name. Encounters match when any participant display name is in this list after case-insensitive whitespace-trimmed comparison. Prefer `learner_emails` because display names are not stable identifiers.\n",
            min_length=1,
        ),
    ] = None
    file_type: FileTypeCode
    expected_count: Annotated[int, Field(ge=0)]


class BulkLearnerUpsertRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[List[BulkLearnerUpsertItem], Field(min_length=1)]


class BulkLearnerUpsertError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: BulkLearnerUpsertErrorCode
    detail: str


class CohortLearnerLinkError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: CohortLearnerLinkErrorCode
    detail: str


class LearnerSummaryWithEffect(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner_id: UUID
    learner_name: str
    email: EmailStr
    learner_entry: LearnerEntry


class LearnerUpsertWithEffectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    learner_id: UUID
    email: EmailStr
    learner_name: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    learner_entry: LearnerEntry


class UploadByIdBulkMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    encounter_id: Annotated[UUID, Field(description="Existing encounter ID")]
    file_type: Annotated[FileTypeCode, Field(description="Logical file type code")]
    file_name: Annotated[
        str,
        Field(description="Original file name (used to link metadata to the right binary file)"),
    ]
    additional_file_identifier: Annotated[
        Optional[int],
        Field(description="Optional caller-defined integer identifier for this file."),
    ] = None


class UploadByIdMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    encounter_id: Annotated[
        UUID,
        Field(description="Application-defined key that identifies an existing encounter."),
    ]
    file_type: FileTypeCode
    additional_file_identifier: Annotated[
        Optional[int],
        Field(description="Optional caller-defined integer identifier for this file."),
    ] = None


class BulkLearnerUpsertItemResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int
    email: str
    learner_id: Optional[UUID] = None
    learner_name: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    learner_entry: Optional[BulkLearnerEntry] = None
    status: int
    message: str
    error: Optional[BulkLearnerUpsertError] = None


class CohortLearnerUpsertResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int
    email: str
    learner_id: Optional[UUID] = None
    learner_name: Optional[str] = None
    link_entry: Optional[CohortLinkEntry] = None
    status: int
    message: str
    error: Optional[CohortLearnerLinkError] = None


class BulkLearnerUpsertResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: BulkLearnerUpsertSummary
    results: List[BulkLearnerUpsertItemResult]


class CohortUpsertResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cohort_id: UUID
    cohort_name: str
    cohort_entry: CohortEntry
    summary: CohortUpsertSummary
    results: List[CohortLearnerUpsertResult]
